# Generated by Django 4.2.9 on 2025-02-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Ежедневный'), ('weekly', 'Еженедельный'), ('monthly', 'Ежемесячный'), ('campaign', 'По кампании'), ('client', 'По клиенту'), ('custom', 'Пользовательский')], max_length=10, verbose_name='Тип отчета')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Начало периода')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Конец периода')),
                ('report_data', models.JSONField(verbose_name='Данные отчета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='campaigns.campaign', verbose_name='Кампания')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Данные отчета',
                'verbose_name_plural': 'Данные отчетов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sent_count', models.PositiveIntegerField(default=0, verbose_name='Email отправлено')),
                ('email_open_count', models.PositiveIntegerField(default=0, verbose_name='Email открыто')),
                ('email_click_count', models.PositiveIntegerField(default=0, verbose_name='Email кликов')),
                ('whatsapp_sent_count', models.PositiveIntegerField(default=0, verbose_name='WhatsApp отправлено')),
                ('whatsapp_delivered_count', models.PositiveIntegerField(default=0, verbose_name='WhatsApp доставлено')),
                ('whatsapp_read_count', models.PositiveIntegerField(default=0, verbose_name='WhatsApp прочитано')),
                ('last_email_sent', models.DateTimeField(blank=True, null=True, verbose_name='Последний email отправлен')),
                ('last_email_opened', models.DateTimeField(blank=True, null=True, verbose_name='Последний email открыт')),
                ('last_email_clicked', models.DateTimeField(blank=True, null=True, verbose_name='Последний email клик')),
                ('last_whatsapp_sent', models.DateTimeField(blank=True, null=True, verbose_name='Последний WhatsApp отправлен')),
                ('last_whatsapp_delivered', models.DateTimeField(blank=True, null=True, verbose_name='Последний WhatsApp доставлен')),
                ('last_whatsapp_read', models.DateTimeField(blank=True, null=True, verbose_name='Последний WhatsApp прочитан')),
                ('engagement_score', models.FloatField(default=0.0, verbose_name='Оценка вовлеченности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Вовлеченность клиента',
                'verbose_name_plural': 'Вовлеченность клиентов',
                'ordering': ['-engagement_score'],
            },
        ),
        migrations.CreateModel(
            name='MessageAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10, verbose_name='Тип сообщения')),
                ('date', models.DateField(verbose_name='Дата')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Отправлено')),
                ('delivered_count', models.PositiveIntegerField(default=0, verbose_name='Доставлено')),
                ('open_count', models.PositiveIntegerField(default=0, verbose_name='Открыто')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Кликов')),
                ('unique_open_count', models.PositiveIntegerField(default=0, verbose_name='Уникальных открытий')),
                ('unique_click_count', models.PositiveIntegerField(default=0, verbose_name='Уникальных кликов')),
                ('bounce_count', models.PositiveIntegerField(default=0, verbose_name='Отказов')),
                ('complaint_count', models.PositiveIntegerField(default=0, verbose_name='Жалоб')),
                ('delivery_rate', models.FloatField(default=0.0, verbose_name='Показатель доставки')),
                ('open_rate', models.FloatField(default=0.0, verbose_name='Показатель открытий')),
                ('click_rate', models.FloatField(default=0.0, verbose_name='Показатель кликов')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_analytics', to='campaigns.campaign', verbose_name='Кампания')),
            ],
            options={
                'verbose_name': 'Аналитика сообщений',
                'verbose_name_plural': 'Аналитика сообщений',
                'ordering': ['-date'],
                'unique_together': {('message_type', 'date', 'campaign')},
            },
        ),
    ]
