# Generated by Django 4.2.9 on 2025-02-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название кампании')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('type', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('mixed', 'Смешанная')], max_length=10, verbose_name='Тип кампании')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='По расписанию')),
                ('scheduled_start', models.DateTimeField(blank=True, null=True, verbose_name='Запланированное начало')),
                ('scheduled_end', models.DateTimeField(blank=True, null=True, verbose_name='Запланированное окончание')),
                ('frequency', models.CharField(choices=[('once', 'Однократно'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('custom', 'Пользовательская')], default='once', max_length=10, verbose_name='Частота')),
                ('custom_schedule', models.JSONField(blank=True, null=True, verbose_name='Пользовательское расписание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирована'), ('active', 'Активна'), ('paused', 'Приостановлена'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='draft', max_length=10, verbose_name='Статус')),
                ('max_messages_per_day', models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. сообщений в день')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='Всего получателей')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Отправлено')),
                ('delivered_count', models.PositiveIntegerField(default=0, verbose_name='Доставлено')),
                ('read_count', models.PositiveIntegerField(default=0, verbose_name='Прочитано')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('client_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='clients.clientgroup', verbose_name='Группа клиентов')),
                ('clients', models.ManyToManyField(blank=True, related_name='targeted_campaigns', to='clients.client', verbose_name='Клиенты')),
                ('email_template', models.ForeignKey(blank=True, limit_choices_to={'type': 'email'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_campaigns', to='templates.messagetemplate', verbose_name='Шаблон email')),
                ('whatsapp_template', models.ForeignKey(blank=True, limit_choices_to={'type': 'whatsapp'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_campaigns', to='templates.messagetemplate', verbose_name='Шаблон WhatsApp')),
            ],
            options={
                'verbose_name': 'Кампания',
                'verbose_name_plural': 'Кампании',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('fixed', 'Фиксированное время'), ('recurring', 'Повторяющееся')], max_length=10, verbose_name='Тип расписания')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='Запланированное время')),
                ('days_of_week', models.JSONField(blank=True, null=True, verbose_name='Дни недели')),
                ('time_of_day', models.TimeField(blank=True, null=True, verbose_name='Время дня')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='campaigns.campaign', verbose_name='Кампания')),
            ],
            options={
                'verbose_name': 'Расписание кампании',
                'verbose_name_plural': 'Расписания кампаний',
                'ordering': ['scheduled_time', 'time_of_day'],
            },
        ),
    ]
