# Generated by Django 4.2.9 on 2025-02-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0001_initial'),
        ('clients', '0001_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10, verbose_name='Тип сообщения')),
                ('direction', models.CharField(choices=[('incoming', 'Входящее'), ('outgoing', 'Исходящее')], max_length=10, verbose_name='Направление')),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='От кого (email)')),
                ('from_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='От кого (номер)')),
                ('to_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Кому (email)')),
                ('to_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Кому (номер)')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Текст сообщения')),
                ('has_attachments', models.BooleanField(default=False, verbose_name='Есть вложения')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('queued', 'В очереди'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('read', 'Прочитано'), ('failed', 'Ошибка')], default='draft', max_length=10, verbose_name='Статус')),
                ('status_details', models.TextField(blank=True, null=True, verbose_name='Детали статуса')),
                ('track_opens', models.BooleanField(default=True, verbose_name='Отслеживать открытия')),
                ('track_clicks', models.BooleanField(default=True, verbose_name='Отслеживать клики')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Запланировано на')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='campaigns.campaign', verbose_name='Кампания')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='clients.client', verbose_name='Клиент')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='templates.messagetemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('open', 'Открытие'), ('click', 'Клик'), ('bounce', 'Отказ'), ('complaint', 'Жалоба'), ('delivery', 'Доставка'), ('read', 'Прочтение')], max_length=20, verbose_name='Тип события')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='Время события')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Метаданные')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='messaging.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Событие сообщения',
                'verbose_name_plural': 'События сообщений',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='message_attachments/', verbose_name='Файл')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.PositiveIntegerField(help_text='Размер в байтах', verbose_name='Размер файла')),
                ('content_type', models.CharField(max_length=100, verbose_name='Тип содержимого')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вложение сообщения',
                'verbose_name_plural': 'Вложения сообщений',
            },
        ),
    ]
